name: Secrets
run-name: APRENDIENDO A USAR SECRETOS
on: 
  workflow_dispatch
env:
  USER: Juan
jobs:
  secrets:
    runs-on: ubuntu-latest
    steps:
      - name: secret job
        run: echo "HOLA $USER, tu contraseña es:${{secrets.PASSWORD}}"
